language: python
python:
  - "3.6"
  - "3.7"
install:
- pip install pipenv
- pip install codecov
- pipenv install --dev
# command to run tests
script: 
- pipenv run pytest --cov=./good_smell 
after_success:
  - codecov

deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  on:
    branch: master
    tag: true